# Data parameters
train_dir: 'data/train'
test_dir: 'data/test'
input_shape: [256, 256, 3]  # Height, Width, Channels
batch_size: 8
val_split: 0.2  # 20% of training data for validation

# Model parameters
learning_rate: 0.0001
epochs: 50

# Paths
model_save_dir: 'models/'
result_dir: 'results/'